driver:
  name: vagrant
  network:
#  - ["forwarded_port", {guest: 82, host: 82}]
  - ["forwarded_port", {guest: 8080, host: 8082}]
  - ["private_network", { ip: "33.33.33.13" }]
  
provisioner:
  name: chef_solo
  # take require... out to use latest
  require_chef_omnibus: 11.18

platforms:
  - name: centos-6.5
#    driver:
#      box: centos65
#      box_url: https://s3-us-west-2.amazonaws.com/misheska/vagrant/virtualbox4.3.6/centos65.box
#      gui: true
    
suites:
  - name: default
    run_list:
      - recipe[bundle-apache-java-tomcat-example::default]

